services:
  swapi_api:
    build: ./swapi_api
    image: swapi_api:1.0
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
  swapi_web:
    build: ./swapi_web
    image: swapi_web:1.0
    environment:
      - SERVER_API_URL=http://localhost:8080/
    ports:
      - 80:80
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost
      interval: 5s
      timeout: 5s
      retries: 40